branches:
  only:
  - master
language: python
python:
- 2.7
script:
    - ../buildbot/build.sh scipy-conference/scipy-papers-2014
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - git clone --recursive https://github.com/scipy-conference/openproceedings-buildbot-scipy.git ../buildbot
  - source ../buildbot/prepare.sh
after_success: bash ../buildbot/deploy.sh proceedings/2014
env:
  global:
    - secure: WRUJh+ZuAxcNal0+GWVwMQwvcEX0M9bqfTbKAvVKQhhQWkfd1nKId225YcsJm0e83wI5noW30B5o9RwA9kXHDx42/7kv6xk8E2WET+iSK5nCMTZfiBmg/H0CYm5s3dyf4+SbCwyY1BqY8JH5qnZV1VNgYFQlVtQSaRm9oV2cxiY=
