branches:
  only:
  - master
language: python
python:
- 2.7
script:
    - ../buildbot/build.sh scipy-conference/scipy-papers-2014
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - git clone --recursive https://github.com/scipy-conference/openproceedings-buildbot-scipy.git ../buildbot
  - source ../buildbot/prepare.sh
after_success: ../buildbot/deploy.sh proceedings/2014
env:
  global:
    - secure: eQ6fJ17jLjytryNrOE+iI4fbh/nXjUQDRzffFlt1sWjbzxZMKWgSwEEHfoid94Ia0nhTP6hdwCP9/13sGobhCjJdXWWXuspSw0pEljDWeihSn1hCdOdTmVcqWCkHcxvVNsDOBRNunvBFTf1bVHfRJMwrQeZGFgNXAsgLyHFIXHc=
