branches:
  only:
  - master
language: python
python:
- 2.7
script:
    - ../buildbot/build.sh scipy-conference/scipy-papers-2014
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - git clone --recursive https://github.com/scipy-conference/openproceedings-buildbot-scipy.git ../buildbot
  - source ../buildbot/prepare.sh
after_success: bash ../buildbot/deploy.sh proceedings/2014
env:
  global:
    - secure: XMKHQKwl4/01crdKXkEKzJ2Cq4MxjzOS1B9qacTDml1QYtFuWxhYHRA9vaY43oJtAdGC5Hfsd+EJIv2zJY718O2EL4Aem9rhKeT9Uput+ZU++9kzKl3F34j9KxXY3sERUY8dLBGByzjKzg0PtwlFKmch8Hb6Ui0cliHdZer4Uls=
